import _HomeContainer from "./home";
import _LoginContainer from "./login";
import _PageNotFound from "./404";
import _Dashboard from "./dashboard";
import _CustomerManagement from "./customermanagement";
import _AddCustomer from "./addcustomer";
import _Register from "./register";
import _RestaurantManagement from "./restaurantmanagement";
import _OrdertManagement from "./ordermanagement";
import _UpdateVendor from "./updatevendor";
import _KitchenManagement from "./kitchenmanagement";

export const HomeContainer = _HomeContainer;
export const LoginContainer = _LoginContainer;
export const PageNotFound = _PageNotFound;
export const Dashboard = _Dashboard;
export const CustomerManagement = _CustomerManagement;
export const AddCustomer = _AddCustomer;
export const Register = _Register;
export const RestaurantManagement = _RestaurantManagement;
export const OrdertManagement = _OrdertManagement;
export const UpdateVendor = _UpdateVendor;
export const KitchenManagement = _KitchenManagement;
