import _HomeContainer from "./home";
import _LoginContainer from "./login";
import _PageNotFound from "./404";
import _Dashboard from "./dashboard";
import _CustomerManagement from "./customermanagement";
import _AddCustomer from "./addcustomer";
import _Register from "./register";
import _RestaurantManagement from "./restaurantmanagement";
import _OrdertManagement from "./ordermanagement";
import _UpdateVendor from "./updatevendor";
import _KitchenManagement from "./kitchenmanagementcategory";
import _KitchenMenu from "./kitchenmenu";
import _KitchenManagementAddCategory from "./kitchenmanagementaddcategory";
import _KitchenManagementAddItem from "./kitchenmanagementadditem";
import _OrderDetails from "./orderdetails";

export const HomeContainer = _HomeContainer;
export const LoginContainer = _LoginContainer;
export const PageNotFound = _PageNotFound;
export const Dashboard = _Dashboard;
export const CustomerManagement = _CustomerManagement;
export const AddCustomer = _AddCustomer;
export const Register = _Register;
export const RestaurantManagement = _RestaurantManagement;
export const OrdertManagement = _OrdertManagement;
export const UpdateVendor = _UpdateVendor;
export const KitchenManagement = _KitchenManagement;
export const KitchenMenu = _KitchenMenu;
export const KitchenManagementAddCategory = _KitchenManagementAddCategory;
export const KitchenManagementAddItem = _KitchenManagementAddItem;
export const OrderDetails = _OrderDetails;
