import _Header from "./header";
import _Footer from "./footer";
import _Layout from "./layout";
import _LeftMenu from "./leftmenu";
import _TopMenu from "./topmenu";
import _DataCounter from "./datacounter";
import _Chart from "./chartcomponent";
import _LChart from "./linechart";
import _BChart from "./barchart";
import _CustomerManagementTable from "./customermanagementtable";
import _NewCustomer from "./newcustomer";
import _RestaurantManagementTable from "./restaurantmanagementtable";
import _OrderManagementTable from "./ordermanagementtable";
import _UpdateVendorForm from "./updatevendorform";
import _KitchenManagementTable from "./kitchenmanagementtable";
import _KitchenMenuTable from "./kitchenmenutable";

export const Header = _Header;
export const Footer = _Footer;
export const Layout = _Layout;
export const LeftMenu = _LeftMenu;
export const TopMenu = _TopMenu;
export const DataCounter = _DataCounter;
export const Chart = _Chart;
export const LChart = _LChart;
export const BChart = _BChart;
export const CustomerManagementTable = _CustomerManagementTable;
export const NewCustomer = _NewCustomer;
export const RestaurantManagementTable = _RestaurantManagementTable;
export const OrderManagementTable = _OrderManagementTable;
export const UpdateVendorForm = _UpdateVendorForm;
export const KitchenManagementTable = _KitchenManagementTable;
export const KitchenMenuTable = _KitchenMenuTable;
